language: python
dist: xenial
python: 3.7
sudo: true

env:
  - PACKAGE=vector_search
  - CC_TEST_REPORTER_ID=@REPO_TOKEN@

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install git+https://github.com/DBCDK/pytools.git
  - pip install pytest-cov
  - pip install Sphinx
  - pip install -e .

# command to run tests
script:
  - pytest -s --cov-report=xml --cov=src/$PACKAGE
  - sphinx-apidoc --force -o docs/source/ src/$PACKAGE `pwd`/src/$PACKAGE/tests/
  - python setup.py build_sphinx --fresh-env --all-files --build-dir docs/build
  - make-build-info
  - python setup.py egg_info --tag-build=".${TRAVIS_BUILD_NUMBER}" bdist_wheel

# after_success:
#  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
